// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/payments-era/V1Hierarchy.tsx": () => import("../components/mockups/payments-era/V1Hierarchy.tsx"),
  "./components/mockups/payments-era/V2Interaction.tsx": () => import("../components/mockups/payments-era/V2Interaction.tsx"),
  "./components/mockups/payments-era/V3Accessibility.tsx": () => import("../components/mockups/payments-era/V3Accessibility.tsx")
};
