// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/appointment-workspace/CardGridDashboard.tsx": () => import("../components/mockups/appointment-workspace/CardGridDashboard.tsx"),
  "./components/mockups/appointment-workspace/CommandBarDashboard.tsx": () => import("../components/mockups/appointment-workspace/CommandBarDashboard.tsx"),
  "./components/mockups/appointment-workspace/TabbedWorkspace.tsx": () => import("../components/mockups/appointment-workspace/TabbedWorkspace.tsx"),
  "./components/mockups/billing-layouts/Rail.tsx": () => import("../components/mockups/billing-layouts/Rail.tsx"),
  "./components/mockups/billing-layouts/Tabs.tsx": () => import("../components/mockups/billing-layouts/Tabs.tsx"),
  "./components/mockups/billing-layouts/Unified.tsx": () => import("../components/mockups/billing-layouts/Unified.tsx"),
  "./components/mockups/schedule-variants/ActionTriageQueue.tsx": () => import("../components/mockups/schedule-variants/ActionTriageQueue.tsx"),
  "./components/mockups/schedule-variants/NowPatientCockpit.tsx": () => import("../components/mockups/schedule-variants/NowPatientCockpit.tsx"),
  "./components/mockups/schedule-variants/StatusPipelineBoard.tsx": () => import("../components/mockups/schedule-variants/StatusPipelineBoard.tsx"),
  "./components/mockups/schedule-variants/TimelineDayGrid.tsx": () => import("../components/mockups/schedule-variants/TimelineDayGrid.tsx"),
  "./components/mockups/charges-layouts/SplitView.tsx": () => import("../components/mockups/charges-layouts/SplitView.tsx"),
  "./components/mockups/charges-layouts/TriageCockpit.tsx": () => import("../components/mockups/charges-layouts/TriageCockpit.tsx"),
  "./components/mockups/charges-layouts/WorklistTable.tsx": () => import("../components/mockups/charges-layouts/WorklistTable.tsx"),
  "./components/mockups/payments-era/V1Hierarchy.tsx": () => import("../components/mockups/payments-era/V1Hierarchy.tsx"),
  "./components/mockups/payments-era/V2Interaction.tsx": () => import("../components/mockups/payments-era/V2Interaction.tsx"),
  "./components/mockups/payments-era/V3Accessibility.tsx": () => import("../components/mockups/payments-era/V3Accessibility.tsx"),
  "./components/mockups/security-redesign/ActivityConsole.tsx": () => import("../components/mockups/security-redesign/ActivityConsole.tsx"),
  "./components/mockups/security-redesign/ComplianceScorecard.tsx": () => import("../components/mockups/security-redesign/ComplianceScorecard.tsx"),
  "./components/mockups/security-redesign/Current.tsx": () => import("../components/mockups/security-redesign/Current.tsx"),
  "./components/mockups/security-redesign/PeopleRoster.tsx": () => import("../components/mockups/security-redesign/PeopleRoster.tsx"),
  "./components/mockups/security-redesign/PermissionMatrix.tsx": () => import("../components/mockups/security-redesign/PermissionMatrix.tsx"),
  "./components/mockups/charges-usability/AccessibleReadable.tsx": () => import("../components/mockups/charges-usability/AccessibleReadable.tsx"),
  "./components/mockups/charges-usability/ActionAffordance.tsx": () => import("../components/mockups/charges-usability/ActionAffordance.tsx"),
  "./components/mockups/charges-usability/ClarityHierarchy.tsx": () => import("../components/mockups/charges-usability/ClarityHierarchy.tsx")
};
